# Generated by Django 4.2.4 on 2024-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_information',
            field=models.JSONField(blank=True, default={}, null=True, verbose_name='Other Information'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(max_length=125),
            preserve_default=False,
        ),
    ]
