version: '3.7'

services:
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads=3 --timeout=1000 --max-requests=4000 --max-requests-jitter=100 --access-logfile - --error-logfile - --log-level info"
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://postgres:2E4ph1SADrGiA7VdikXpX57HliC1ARxMmNlgwAtptTcVDe30GUtgutVTXFzX1DVZ@egwcw4wkkg04kwgk4wk4g4os:5432/postgres
  
