# Generated by Django 4.2.4 on 2024-11-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
        ('customer', '0010_alter_return_refund_status_alter_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_returns', to='orders.order', verbose_name='Order'),
        ),
    ]
