# Generated by Django 4.2.4 on 2024-12-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_products_is_wishlisted'),
        ('customer', '0011_return_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', to='product.products', verbose_name='Product'),
        ),
    ]
