# Generated by Django 4.2.4 on 2024-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_lookbook_description_lookbook_feature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=50, null=True),
        ),
    ]
