# Generated by Django 4.2.4 on 2024-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_products_preferred_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Boys', 'Boys'), ('Girls', 'Girls')], max_length=50),
        ),
    ]
