# Generated by Django 4.2.4 on 2024-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_products_preferred_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Gst'),
        ),
        migrations.AlterField(
            model_name='products',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex'), ('Boys', 'Boys'), ('Girls', 'Girls')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Selling Price'),
        ),
    ]
