# Generated by Django 4.2.4 on 2024-11-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_products_gst_alter_products_preferred_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantattributes',
            name='name',
            field=models.CharField(default=0, max_length=256, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
