# Generated by Django 4.2.4 on 2024-11-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('product', '0017_variantattributes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.tax', verbose_name='GST'),
        ),
    ]
