# Generated by Django 4.2.4 on 2024-11-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_products_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='feature_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Feature Image'),
        ),
    ]
