# Generated by Django 4.2.4 on 2024-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_lookbook_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='feature_image',
            field=models.FileField(blank=True, null=True, upload_to='collections/', verbose_name='Image'),
        ),
    ]
