# Generated by Django 4.2.4 on 2024-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_collection_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookbook',
            name='feature_image',
            field=models.FileField(blank=True, null=True, upload_to='lookbook/', verbose_name='Image'),
        ),
    ]
