# Generated by Django 4.2.4 on 2024-11-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_brandget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandGET',
        ),
    ]
