# Generated by Django 4.2.4 on 2024-12-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_delete_brandget'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_wishlisted',
            field=models.BooleanField(default=False, verbose_name='Is Wishlisted'),
        ),
    ]
