# Generated by Django 4.2.4 on 2024-12-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_products_is_wishlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='is_wishlisted',
        ),
    ]
