# Generated by Django 4.2.4 on 2024-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herosection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.CharField(max_length=300, verbose_name='Image'),
        ),
    ]
