# Generated by Django 4.2.4 on 2024-11-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_herosection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='hero_section/', verbose_name='Image'),
        ),
    ]
