# Generated by Django 4.2.4 on 2024-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_herosection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='is_in_shop_page',
            field=models.BooleanField(default=False, verbose_name='Is in Shop Page'),
        ),
    ]
