# Generated by Django 4.2.4 on 2024-11-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_alter_brand_logo_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='brand/', verbose_name='Image'),
        ),
    ]
