# Generated by Django 4.2.4 on 2024-12-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Name'),
        ),
    ]
